<?php include './templates/header.phtml'; ?>
<link rel="stylesheet" href="css/style.css">
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <div class="card shadow-lg bg-dark text-light border-0">
                <div class="card-header text-center fs-4 fw-bold bg-gradient">
                    Editar Banda
                </div>
                <div class="card-body">
                    <form action="bandas/actualizar/<?= $banda->id_banda ?>" method="POST">
                        <input type="hidden" name="id" value="<?= $banda->id_banda ?>">

                        <!-- Nombre -->
                        <div class="mb-3">
                            <label for="nombre" class="form-label">Nuevo Nombre de Banda</label>
                            <input type="text" class="form-control bg-dark text-light border-secondary" id="nombre" name="nombre">
                        </div>

                        <!-- País -->
                        <div class="mb-3">
                            <label for="pais" class="form-label">Nuevo País de Origen</label>
                            <input type="text" class="form-control bg-dark text-light border-secondary" id="pais" name="pais">
                        </div>

                        <!-- Género -->
                        <div class="mb-3">
                            <label for="genero" class="form-label">Nuevo Género Musical</label>
                            <input type="text" class="form-control bg-dark text-light border-secondary" id="genero" name="genero">
                        </div>

                        <!-- Imagen -->
                        <div class="mb-3">
                            <label for="imagen" class="form-label">URL de Imagen Nueva</label>
                            <input type="url" class="form-control bg-dark text-light border-secondary" id="imagen" name="imagen">
                            <div class="form-text text-secondary">Pegá Nuevo enlace de imagen</div>
                        </div>

                        <!-- Botón -->
                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-outline-light px-4 py-2">Editar Banda</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include './templates/footer.phtml'; ?>
