<link rel="stylesheet" href="css/style.css">
<footer class="bg-dark text-light pt-4 pb-3 mt-5">
    <div class="container text-center text-md-start">
        <div class="row">

            <div class="col-md-4 mb-3">
                <h5 class="fw-bold">ArgenRock</h5>
                <p>Descubrí tus bandas favoritas y sus próximos conciertos.</p>
            </div>

            <div class="col-md-4 mb-3">
                <h6 class="fw-bold">Enlaces</h6>
                <ul class="list-unstyled">
                    <li><a href="bandas" class="text-light text-decoration-none">Inicio</a></li>
                    <li><a href="bandas" class="text-light text-decoration-none">Bandas</a></li>
                    <li><a href="conciertos" class="text-light text-decoration-none">Conciertos</a></li>
                </ul>
            </div>

            <div class="col-md-4 mb-3">
                <h6 class="fw-bold">Contacto</h6>
                <p>ArgenRock@gmail.com</p>
            </div>

        </div>

        <hr class="border-light">

        <div class="text-center">
            <small>2025 ArgenRock. Todos los derechos reservados.</small>
        </div>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>