<?php include_once './templates/header.phtml' ?>

<link rel="stylesheet" href="css/style.css">
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <div class="card shadow-lg bg-dark text-light border-0">
                <div class="card-header text-center fs-4 fw-bold bg-gradient">
                    Iniciar Sesion
                </div>
                <div class="card-body">
                    <form action="bandas/ingresar" method="POST">
                        <div class="mb-3">
                            <label class="form-label">Usuario</label>
                            <input type="text" class="form-control bg-dark text-light border-secondary" name="usuario" required>
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Contraseña</label>
                            <input type="password" class="form-control bg-dark text-light border-secondary" name="contraseña" required>
                        </div>

                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-outline-light px-4 py-2">Ingresar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include_once './templates/footer.phtml' ?>