<?php include './templates/header.phtml'; ?>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<div class="container py-5">
    <div class="card mx-auto shadow-lg border-0" style="max-width: 600px;">
        <div class="card-body text-center">
            <h5 class="card-title">Concierto <?= $conciertoData->id_concierto ?> </h5>
            <h3 class="card-title"><?= $conciertoData->Fecha ?></h3>
            <p class="card-text"><strong>Horario:</strong> <?= $conciertoData->Horario ?></p>
            <p class="card-text"><strong>Lugar:</strong> <?= $conciertoData->Lugar ?></p>
            <p class="card-text"><strong>Ciudad:</strong> <?= $conciertoData->Ciudad ?></p>
            <p class="card-text"><strong>Banda:</strong> <?= $conciertoData->id_banda ?></p>
            <a href="bandas" class="btn btn-primary mt-3">Volver al listado</a>
        </div>
    </div>
</div>

<?php include './templates/footer.phtml'; ?>